---
title: "Working with NSDUH Data in R"
author: "Collin Miller"
date: "October 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "", fig.width=8.4)
```

##Description of Data

TO BE COMPLETED
TABLE OF VARIABLES 

## Load Data

```{r, warning=FALSE, message=FALSE}
load("nsduh_female_dat_2015.rda")
```

## Examine Structure and Variables 

```{r, warning=FALSE, message=FALSE}
#Structure
str(fem.d, give.att = FALSE)

#Glimpse with dplyr
library(dplyr)
glimpse(fem.d)

#dim - dimensions (rows/observations and columns/variables)
dim(fem.d)
```


##Clean Variables

```{r}

fem.d$irsex.f <- factor(fem.d$irsex,
                        labels = c("Female"))

#Loop for recoding abuse and dependence into factors

fact_list <- names(fem.d[4:31])

for (k in fact_list){
  fem.d[k][fem.d[k]== 0] <- "No"
  fem.d[k][fem.d[k]== 1] <- "Yes"
}

#Convert to factors
fem.d[,fact_list] <- lapply(fem.d[,fact_list], factor)

#Race
fem.d$NEWRACE2.f <- factor(fem.d$NEWRACE2,
                           labels = c("White", "Black", "Native Am/AK Native",
                                      "Native HI/Other Pac Isl", "Asian", "Multi-racial",
                                      "Hispanic"))

#Education

fem.d$eduhighcat.f <- factor(fem.d$eduhighcat,
                             labels = c("Less high school", "High school grad", "Some col/Assoc Dg", "College graduate", "12-17 years old"))

#Employment

fem.d$irwrkstat.f <- factor(fem.d$irwrkstat,
                            labels = c("Employed full time", "Employed part time" , "Unemployed", "Other - not in labor force", "12-14 years old"))


#Medicaid status

fem.d$irmcdchp.f <- factor(fem.d$irmcdchp,
                           labels = c("Yes, Medicaid/CHIP", "No, Medicaid/CHIP"))


#Major depressive disorder in past year - Adult


fem.d$amdeyr.f <- factor(fem.d$amdeyr,
                         labels = c("Yes", "No"))

#Major depressive disorder in past year - Youth

fem.d$ymdeyr.f <- factor(fem.d$ymdeyr,
                         labels = c("Yes", "No"))

#Age

fem.d$CATAG6.f <- factor(fem.d$CATAG6,
                         labels = c("12-17", "18-25", "26-34", "35-49", "50-64", "64 or Older"))

#Sexual Identity
fem.d$sexident.f <- cut(fem.d$sexident, 
                    breaks = c(0, 1, 2, 3, Inf),
                    labels = c("Heterosexual", "Lesbian or Gay", "Bisexual", "NA"))
#NA categorical as NA value
fem.d$sexident.f[fem.d$sexident.f == "NA"] <- NA
#Drop levels with 0 observations
fem.d$sexident.f <- droplevels(fem.d$sexident.f)
```

#Visually Inspect Data 

```{r, warning=FALSE, message=FALSE}
#install.packages("DT")
library(DT)
datatable(fem.d[1:500, ])
```

#Descriptive Statistics

##Frequencies
```{r, warning=FALSE, message=FALSE}
#Age distribtution
library(descr)

freq(fem.d$CATAG6.f)
freq(fem.d$NEWRACE2.f)
freq(fem.d$eduhighcat.f)
freq(fem.d$irwrkstat.f)
freq(fem.d$irmcdchp.f)
freq(fem.d$amdeyr.f)
freq(fem.d$ymdeyr.f)
freq(fem.d$sexident.f)

```

##Crosstabs


```{r, echo=TRUE,results='asis', message=FALSE, warning=FALSE}
library(pander)
x <- xtabs(~NEWRACE2.f+depndalc, data = fem.d)
y <- xtabs(~sexident.f+depndalc, data = fem.d)
pander(x)
pander(y)
```

##Transform for Visualizing Drug Dependence and Drug Abuse Variables

###Dependence

```{r, warning=FALSE, message=FALSE}
library(tidyr)
library(ggplot2)

depnd.d <- fem.d %>%
  select(QUESTID2, starts_with("depnd")) %>%
  gather("substance","value", 2:15) %>%
  mutate(sub = substring(substance, 6)) %>%
  filter(value == "Yes") %>%
  group_by(sub) %>%
  tally() %>%
  arrange(desc(n))
  

depnd.fig <- ggplot(data = depnd.d, aes(x = reorder(sub, -n), y=n)) +
  geom_bar(stat="identity")

depnd.fig

```